### ISSUE TITLE
faster query performance - add indexing on View key composite

### ISSUE THREAD

**Issue by wallabyway** [petrbroz/forge-props-service#2]
CREATE INDEX etc

**Comment by petrbroz** [comment]
Good idea. What kinds of indices would you recommend? Here's what I've done for now:

- tried adding a composite index by `prop_name` and `prop_value` to the `properties` view but as it turns out, you cannot create indices to views...
- added simple indices for individual keys: one for `attr_category`, one for `attr_name`, one for `attr_value`, one for `dbid`, and one for `external_id`.

**Comment by petrbroz** [comment]
Btw. these are the indices I've added for now:

```sql
CREATE INDEX idx_external_id ON objects_ids (external_id);
CREATE INDEX idx_attr_category ON objects_attrs (category);
CREATE INDEX idx_attr_name ON objects_attrs (name);
CREATE INDEX idx_attr_value ON objects_vals (value);
CREATE INDEX idx_dbid ON objects_avs (ent_id);
CREATE INDEX idx_attr_id_val_id ON objects_avs (attr_id, val_id);
```
